# Generated by Django 2.2.16 on 2020-11-17 11:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0005_create_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 11, 37, 3, 399593, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
